//basic syntax for Jenkinsfile
pipeline {
    agent any
    stages{
      stage('build'){
            steps{
                echo 'building the application'
            }
        } 
        stage('test'){
            steps{
                echo 'testing application'
            }
        }
        stage('deploy'){
            steps{
               echo 'deploying application' 
            }
        }
        stage('path added'){
            steps{
               echo 'path adding' 
            }
        }
    }
}
