pipeline {
    agent any

    parameters {
        choice(name: 'VERSION', choices: ['1.1.1', '1.2.3'. '1.4.5'])
        booleanParam(name: 'default', defaultValue: true)
    }

    stages {
        stage('build') {
            steps {
                echo "Building project"
                // Add your build steps here
            }
        }
        stage('test') {
            steps {
                echo "Testing project"
                // Add your test steps here
            }
        }
        stage('deploy') {
            steps {
                echo "Deploying version ${VERSION}"
                // Add your deploy steps here
            }
        }
    }
}
